// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/sf/substreams/sink/kafka/v1/block_reorg.proto

package pbkafka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockReorg struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	LastValidCursor                string                 `protobuf:"bytes,1,opt,name=last_valid_cursor,json=lastValidCursor,proto3" json:"last_valid_cursor,omitempty"`
	LastValidBlockId               string                 `protobuf:"bytes,2,opt,name=last_valid_block_id,json=lastValidBlockId,proto3" json:"last_valid_block_id,omitempty"`
	LastValidBlockNumber           uint64                 `protobuf:"varint,3,opt,name=last_valid_block_number,json=lastValidBlockNumber,proto3" json:"last_valid_block_number,omitempty"`
	SubstreamNotificationTimestamp uint64                 `protobuf:"varint,4,opt,name=substream_notification_timestamp,json=substreamNotificationTimestamp,proto3" json:"substream_notification_timestamp,omitempty"` // unix seconds when notification was handled
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *BlockReorg) Reset() {
	*x = BlockReorg{}
	mi := &file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReorg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReorg) ProtoMessage() {}

func (x *BlockReorg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReorg.ProtoReflect.Descriptor instead.
func (*BlockReorg) Descriptor() ([]byte, []int) {
	return file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDescGZIP(), []int{0}
}

func (x *BlockReorg) GetLastValidCursor() string {
	if x != nil {
		return x.LastValidCursor
	}
	return ""
}

func (x *BlockReorg) GetLastValidBlockId() string {
	if x != nil {
		return x.LastValidBlockId
	}
	return ""
}

func (x *BlockReorg) GetLastValidBlockNumber() uint64 {
	if x != nil {
		return x.LastValidBlockNumber
	}
	return 0
}

func (x *BlockReorg) GetSubstreamNotificationTimestamp() uint64 {
	if x != nil {
		return x.SubstreamNotificationTimestamp
	}
	return 0
}

var File_proto_sf_substreams_sink_kafka_v1_block_reorg_proto protoreflect.FileDescriptor

const file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDesc = "" +
	"\n" +
	"3proto/sf/substreams/sink/kafka/v1/block_reorg.proto\x12\x1bsf.substreams.sink.kafka.v1\"\xe8\x01\n" +
	"\n" +
	"BlockReorg\x12*\n" +
	"\x11last_valid_cursor\x18\x01 \x01(\tR\x0flastValidCursor\x12-\n" +
	"\x13last_valid_block_id\x18\x02 \x01(\tR\x10lastValidBlockId\x125\n" +
	"\x17last_valid_block_number\x18\x03 \x01(\x04R\x14lastValidBlockNumber\x12H\n" +
	" substream_notification_timestamp\x18\x04 \x01(\x04R\x1esubstreamNotificationTimestampB\\ZZgithub.com/Data-Nexus-Web3/substreams-sink-kafka/proto/sf/substreams/sink/kafka/v1;pbkafkab\x06proto3"

var (
	file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDescOnce sync.Once
	file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDescData []byte
)

func file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDescGZIP() []byte {
	file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDescOnce.Do(func() {
		file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDesc), len(file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDesc)))
	})
	return file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDescData
}

var file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_goTypes = []any{
	(*BlockReorg)(nil), // 0: sf.substreams.sink.kafka.v1.BlockReorg
}
var file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_init() }
func file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_init() {
	if File_proto_sf_substreams_sink_kafka_v1_block_reorg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDesc), len(file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_goTypes,
		DependencyIndexes: file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_depIdxs,
		MessageInfos:      file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_msgTypes,
	}.Build()
	File_proto_sf_substreams_sink_kafka_v1_block_reorg_proto = out.File
	file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_goTypes = nil
	file_proto_sf_substreams_sink_kafka_v1_block_reorg_proto_depIdxs = nil
}
