// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/sf/substreams/sink/kafka/v1/exploded.proto

package pbkafka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExplodedRecord represents a single exploded record from a repeated field
type ExplodedRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original field name that was exploded
	SourceField string `protobuf:"bytes,1,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`
	// The exploded data as a flexible structure
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Parent context fields (from include_parent_fields annotation)
	ParentContext *structpb.Struct `protobuf:"bytes,3,opt,name=parent_context,json=parentContext,proto3" json:"parent_context,omitempty"`
	// Index of this item in the original repeated field
	ItemIndex int32 `protobuf:"varint,4,opt,name=item_index,json=itemIndex,proto3" json:"item_index,omitempty"`
	// Original cursor/metadata
	Cursor string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Additional metadata
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplodedRecord) Reset() {
	*x = ExplodedRecord{}
	mi := &file_proto_sf_substreams_sink_kafka_v1_exploded_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplodedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplodedRecord) ProtoMessage() {}

func (x *ExplodedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sf_substreams_sink_kafka_v1_exploded_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplodedRecord.ProtoReflect.Descriptor instead.
func (*ExplodedRecord) Descriptor() ([]byte, []int) {
	return file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDescGZIP(), []int{0}
}

func (x *ExplodedRecord) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

func (x *ExplodedRecord) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExplodedRecord) GetParentContext() *structpb.Struct {
	if x != nil {
		return x.ParentContext
	}
	return nil
}

func (x *ExplodedRecord) GetItemIndex() int32 {
	if x != nil {
		return x.ItemIndex
	}
	return 0
}

func (x *ExplodedRecord) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ExplodedRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_sf_substreams_sink_kafka_v1_exploded_proto protoreflect.FileDescriptor

const file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDesc = "" +
	"\n" +
	"0proto/sf/substreams/sink/kafka/v1/exploded.proto\x12\x1bsf.substreams.sink.kafka.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xeb\x02\n" +
	"\x0eExplodedRecord\x12!\n" +
	"\fsource_field\x18\x01 \x01(\tR\vsourceField\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12>\n" +
	"\x0eparent_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\rparentContext\x12\x1d\n" +
	"\n" +
	"item_index\x18\x04 \x01(\x05R\titemIndex\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12U\n" +
	"\bmetadata\x18\x06 \x03(\v29.sf.substreams.sink.kafka.v1.ExplodedRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BZZXgithub.com/streamingfast/substreams-sink-kafka/proto/sf/substreams/sink/kafka/v1;pbkafkab\x06proto3"

var (
	file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDescOnce sync.Once
	file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDescData []byte
)

func file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDescGZIP() []byte {
	file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDescOnce.Do(func() {
		file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDesc), len(file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDesc)))
	})
	return file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDescData
}

var file_proto_sf_substreams_sink_kafka_v1_exploded_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sf_substreams_sink_kafka_v1_exploded_proto_goTypes = []any{
	(*ExplodedRecord)(nil),  // 0: sf.substreams.sink.kafka.v1.ExplodedRecord
	nil,                     // 1: sf.substreams.sink.kafka.v1.ExplodedRecord.MetadataEntry
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_proto_sf_substreams_sink_kafka_v1_exploded_proto_depIdxs = []int32{
	2, // 0: sf.substreams.sink.kafka.v1.ExplodedRecord.data:type_name -> google.protobuf.Struct
	2, // 1: sf.substreams.sink.kafka.v1.ExplodedRecord.parent_context:type_name -> google.protobuf.Struct
	1, // 2: sf.substreams.sink.kafka.v1.ExplodedRecord.metadata:type_name -> sf.substreams.sink.kafka.v1.ExplodedRecord.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sf_substreams_sink_kafka_v1_exploded_proto_init() }
func file_proto_sf_substreams_sink_kafka_v1_exploded_proto_init() {
	if File_proto_sf_substreams_sink_kafka_v1_exploded_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDesc), len(file_proto_sf_substreams_sink_kafka_v1_exploded_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sf_substreams_sink_kafka_v1_exploded_proto_goTypes,
		DependencyIndexes: file_proto_sf_substreams_sink_kafka_v1_exploded_proto_depIdxs,
		MessageInfos:      file_proto_sf_substreams_sink_kafka_v1_exploded_proto_msgTypes,
	}.Build()
	File_proto_sf_substreams_sink_kafka_v1_exploded_proto = out.File
	file_proto_sf_substreams_sink_kafka_v1_exploded_proto_goTypes = nil
	file_proto_sf_substreams_sink_kafka_v1_exploded_proto_depIdxs = nil
}
