// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/token_metadata/v1/service.proto

package tokenmetadatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_token_metadata_v1_service_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_token_metadata_v1_service_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{10, 0}
}

type BatchTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber    uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TokenAddresses []string               `protobuf:"bytes,2,rep,name=token_addresses,json=tokenAddresses,proto3" json:"token_addresses,omitempty"` // Ethereum addresses (0x...)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchTokenRequest) Reset() {
	*x = BatchTokenRequest{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTokenRequest) ProtoMessage() {}

func (x *BatchTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTokenRequest.ProtoReflect.Descriptor instead.
func (*BatchTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *BatchTokenRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BatchTokenRequest) GetTokenAddresses() []string {
	if x != nil {
		return x.TokenAddresses
	}
	return nil
}

type BatchTokenResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Tokens        map[string]*TokenMetadata `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // address -> metadata
	NotFound      []string                  `protobuf:"bytes,2,rep,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`                                                       // addresses that weren't found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTokenResponse) Reset() {
	*x = BatchTokenResponse{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTokenResponse) ProtoMessage() {}

func (x *BatchTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTokenResponse.ProtoReflect.Descriptor instead.
func (*BatchTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchTokenResponse) GetTokens() map[string]*TokenMetadata {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *BatchTokenResponse) GetNotFound() []string {
	if x != nil {
		return x.NotFound
	}
	return nil
}

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *TokenRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *TokenMetadata         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *TokenResponse) GetToken() *TokenMetadata {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TokenResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type TokenMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                                        // Contract address
	Decimals       uint32                 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`                                     // Token decimals (usually 18)
	Symbol         string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                          // Token symbol (e.g., "USDC") - up to 64 chars
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                              // Token name (e.g., "USD Coin") - up to 512 chars
	ValidFromBlock uint64                 `protobuf:"varint,5,opt,name=valid_from_block,json=validFromBlock,proto3" json:"valid_from_block,omitempty"` // Block when token was created
	ValidToBlock   uint64                 `protobuf:"varint,6,opt,name=valid_to_block,json=validToBlock,proto3" json:"valid_to_block,omitempty"`       // Block when token was upgraded (0 = current)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenMetadata) Reset() {
	*x = TokenMetadata{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetadata) ProtoMessage() {}

func (x *TokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetadata.ProtoReflect.Descriptor instead.
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *TokenMetadata) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenMetadata) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenMetadata) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenMetadata) GetValidFromBlock() uint64 {
	if x != nil {
		return x.ValidFromBlock
	}
	return 0
}

func (x *TokenMetadata) GetValidToBlock() uint64 {
	if x != nil {
		return x.ValidToBlock
	}
	return 0
}

type BatchNormalizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Amounts       []*TokenAmountPair     `protobuf:"bytes,2,rep,name=amounts,proto3" json:"amounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchNormalizeRequest) Reset() {
	*x = BatchNormalizeRequest{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchNormalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchNormalizeRequest) ProtoMessage() {}

func (x *BatchNormalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchNormalizeRequest.ProtoReflect.Descriptor instead.
func (*BatchNormalizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchNormalizeRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BatchNormalizeRequest) GetAmounts() []*TokenAmountPair {
	if x != nil {
		return x.Amounts
	}
	return nil
}

type TokenAmountPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	RawAmount     string                 `protobuf:"bytes,2,opt,name=raw_amount,json=rawAmount,proto3" json:"raw_amount,omitempty"` // Raw uint256 as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenAmountPair) Reset() {
	*x = TokenAmountPair{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenAmountPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAmountPair) ProtoMessage() {}

func (x *TokenAmountPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAmountPair.ProtoReflect.Descriptor instead.
func (*TokenAmountPair) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *TokenAmountPair) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenAmountPair) GetRawAmount() string {
	if x != nil {
		return x.RawAmount
	}
	return ""
}

type BatchNormalizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Normalized    []*NormalizedAmount    `protobuf:"bytes,1,rep,name=normalized,proto3" json:"normalized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchNormalizeResponse) Reset() {
	*x = BatchNormalizeResponse{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchNormalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchNormalizeResponse) ProtoMessage() {}

func (x *BatchNormalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchNormalizeResponse.ProtoReflect.Descriptor instead.
func (*BatchNormalizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *BatchNormalizeResponse) GetNormalized() []*NormalizedAmount {
	if x != nil {
		return x.Normalized
	}
	return nil
}

type NormalizedAmount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress    string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	RawAmount       string                 `protobuf:"bytes,2,opt,name=raw_amount,json=rawAmount,proto3" json:"raw_amount,omitempty"`
	FormattedAmount string                 `protobuf:"bytes,3,opt,name=formatted_amount,json=formattedAmount,proto3" json:"formatted_amount,omitempty"` // Decimal formatted amount
	Success         bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Error message if success=false
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NormalizedAmount) Reset() {
	*x = NormalizedAmount{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedAmount) ProtoMessage() {}

func (x *NormalizedAmount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedAmount.ProtoReflect.Descriptor instead.
func (*NormalizedAmount) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *NormalizedAmount) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *NormalizedAmount) GetRawAmount() string {
	if x != nil {
		return x.RawAmount
	}
	return ""
}

func (x *NormalizedAmount) GetFormattedAmount() string {
	if x != nil {
		return x.FormattedAmount
	}
	return ""
}

func (x *NormalizedAmount) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NormalizedAmount) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=token_metadata.v1.HealthResponse_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_metadata_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_metadata_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_token_metadata_v1_service_proto protoreflect.FileDescriptor

const file_proto_token_metadata_v1_service_proto_rawDesc = "" +
	"\n" +
	"%proto/token_metadata/v1/service.proto\x12\x11token_metadata.v1\"_\n" +
	"\x11BatchTokenRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12'\n" +
	"\x0ftoken_addresses\x18\x02 \x03(\tR\x0etokenAddresses\"\xd9\x01\n" +
	"\x12BatchTokenResponse\x12I\n" +
	"\x06tokens\x18\x01 \x03(\v21.token_metadata.v1.BatchTokenResponse.TokensEntryR\x06tokens\x12\x1b\n" +
	"\tnot_found\x18\x02 \x03(\tR\bnotFound\x1a[\n" +
	"\vTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .token_metadata.v1.TokenMetadataR\x05value:\x028\x01\"V\n" +
	"\fTokenRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\"]\n" +
	"\rTokenResponse\x126\n" +
	"\x05token\x18\x01 \x01(\v2 .token_metadata.v1.TokenMetadataR\x05token\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xc1\x01\n" +
	"\rTokenMetadata\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12(\n" +
	"\x10valid_from_block\x18\x05 \x01(\x04R\x0evalidFromBlock\x12$\n" +
	"\x0evalid_to_block\x18\x06 \x01(\x04R\fvalidToBlock\"x\n" +
	"\x15BatchNormalizeRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12<\n" +
	"\aamounts\x18\x02 \x03(\v2\".token_metadata.v1.TokenAmountPairR\aamounts\"U\n" +
	"\x0fTokenAmountPair\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x1d\n" +
	"\n" +
	"raw_amount\x18\x02 \x01(\tR\trawAmount\"]\n" +
	"\x16BatchNormalizeResponse\x12C\n" +
	"\n" +
	"normalized\x18\x01 \x03(\v2#.token_metadata.v1.NormalizedAmountR\n" +
	"normalized\"\xb1\x01\n" +
	"\x10NormalizedAmount\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x1d\n" +
	"\n" +
	"raw_amount\x18\x02 \x01(\tR\trawAmount\x12)\n" +
	"\x10formatted_amount\x18\x03 \x01(\tR\x0fformattedAmount\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"\xa1\x01\n" +
	"\x0eHealthResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.token_metadata.v1.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x95\x03\n" +
	"\x14TokenMetadataService\x12d\n" +
	"\x15BatchGetTokenMetadata\x12$.token_metadata.v1.BatchTokenRequest\x1a%.token_metadata.v1.BatchTokenResponse\x12U\n" +
	"\x10GetTokenMetadata\x12\x1f.token_metadata.v1.TokenRequest\x1a .token_metadata.v1.TokenResponse\x12q\n" +
	"\x1aBatchNormalizeTokenAmounts\x12(.token_metadata.v1.BatchNormalizeRequest\x1a).token_metadata.v1.BatchNormalizeResponse\x12M\n" +
	"\x06Health\x12 .token_metadata.v1.HealthRequest\x1a!.token_metadata.v1.HealthResponseBXZVgithub.com/streamingfast/substreams-sink-kafka/proto/token_metadata/v1;tokenmetadatav1b\x06proto3"

var (
	file_proto_token_metadata_v1_service_proto_rawDescOnce sync.Once
	file_proto_token_metadata_v1_service_proto_rawDescData []byte
)

func file_proto_token_metadata_v1_service_proto_rawDescGZIP() []byte {
	file_proto_token_metadata_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_token_metadata_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_metadata_v1_service_proto_rawDesc), len(file_proto_token_metadata_v1_service_proto_rawDesc)))
	})
	return file_proto_token_metadata_v1_service_proto_rawDescData
}

var file_proto_token_metadata_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_token_metadata_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_token_metadata_v1_service_proto_goTypes = []any{
	(HealthResponse_Status)(0),     // 0: token_metadata.v1.HealthResponse.Status
	(*BatchTokenRequest)(nil),      // 1: token_metadata.v1.BatchTokenRequest
	(*BatchTokenResponse)(nil),     // 2: token_metadata.v1.BatchTokenResponse
	(*TokenRequest)(nil),           // 3: token_metadata.v1.TokenRequest
	(*TokenResponse)(nil),          // 4: token_metadata.v1.TokenResponse
	(*TokenMetadata)(nil),          // 5: token_metadata.v1.TokenMetadata
	(*BatchNormalizeRequest)(nil),  // 6: token_metadata.v1.BatchNormalizeRequest
	(*TokenAmountPair)(nil),        // 7: token_metadata.v1.TokenAmountPair
	(*BatchNormalizeResponse)(nil), // 8: token_metadata.v1.BatchNormalizeResponse
	(*NormalizedAmount)(nil),       // 9: token_metadata.v1.NormalizedAmount
	(*HealthRequest)(nil),          // 10: token_metadata.v1.HealthRequest
	(*HealthResponse)(nil),         // 11: token_metadata.v1.HealthResponse
	nil,                            // 12: token_metadata.v1.BatchTokenResponse.TokensEntry
}
var file_proto_token_metadata_v1_service_proto_depIdxs = []int32{
	12, // 0: token_metadata.v1.BatchTokenResponse.tokens:type_name -> token_metadata.v1.BatchTokenResponse.TokensEntry
	5,  // 1: token_metadata.v1.TokenResponse.token:type_name -> token_metadata.v1.TokenMetadata
	7,  // 2: token_metadata.v1.BatchNormalizeRequest.amounts:type_name -> token_metadata.v1.TokenAmountPair
	9,  // 3: token_metadata.v1.BatchNormalizeResponse.normalized:type_name -> token_metadata.v1.NormalizedAmount
	0,  // 4: token_metadata.v1.HealthResponse.status:type_name -> token_metadata.v1.HealthResponse.Status
	5,  // 5: token_metadata.v1.BatchTokenResponse.TokensEntry.value:type_name -> token_metadata.v1.TokenMetadata
	1,  // 6: token_metadata.v1.TokenMetadataService.BatchGetTokenMetadata:input_type -> token_metadata.v1.BatchTokenRequest
	3,  // 7: token_metadata.v1.TokenMetadataService.GetTokenMetadata:input_type -> token_metadata.v1.TokenRequest
	6,  // 8: token_metadata.v1.TokenMetadataService.BatchNormalizeTokenAmounts:input_type -> token_metadata.v1.BatchNormalizeRequest
	10, // 9: token_metadata.v1.TokenMetadataService.Health:input_type -> token_metadata.v1.HealthRequest
	2,  // 10: token_metadata.v1.TokenMetadataService.BatchGetTokenMetadata:output_type -> token_metadata.v1.BatchTokenResponse
	4,  // 11: token_metadata.v1.TokenMetadataService.GetTokenMetadata:output_type -> token_metadata.v1.TokenResponse
	8,  // 12: token_metadata.v1.TokenMetadataService.BatchNormalizeTokenAmounts:output_type -> token_metadata.v1.BatchNormalizeResponse
	11, // 13: token_metadata.v1.TokenMetadataService.Health:output_type -> token_metadata.v1.HealthResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_token_metadata_v1_service_proto_init() }
func file_proto_token_metadata_v1_service_proto_init() {
	if File_proto_token_metadata_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_metadata_v1_service_proto_rawDesc), len(file_proto_token_metadata_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_metadata_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_token_metadata_v1_service_proto_depIdxs,
		EnumInfos:         file_proto_token_metadata_v1_service_proto_enumTypes,
		MessageInfos:      file_proto_token_metadata_v1_service_proto_msgTypes,
	}.Build()
	File_proto_token_metadata_v1_service_proto = out.File
	file_proto_token_metadata_v1_service_proto_goTypes = nil
	file_proto_token_metadata_v1_service_proto_depIdxs = nil
}
