-- Simplified Snowflake Setup for ADR Kafka Connector with Snowpipe Streaming
-- Using existing SENTINEL_DB_ADMIN role - no new roles or users needed

-- 1. Ensure database and schema exist (they likely already do)
USE ROLE SENTINEL_DB_ADMIN;
CREATE DATABASE IF NOT EXISTS SENTINEL_DB;
CREATE SCHEMA IF NOT EXISTS SENTINEL_DB.STREAMING_SCHEMA;

-- 2. Create target table for ADR data
USE DATABASE SENTINEL_DB;
USE SCHEMA STREAMING_SCHEMA;

CREATE TABLE IF NOT EXISTS ADR_LISTENER_MESSAGES (
  RECORD_METADATA VARIANT,
  RECORD_CONTENT VARIANT
);

-- Enable schema evolution for automatic field detection
ALTER TABLE ADR_LISTENER_MESSAGES SET ENABLE_SCHEMA_EVOLUTION = TRUE;

-- 3. Create dead letter queue table for error handling
CREATE TABLE IF NOT EXISTS SNOWFLAKE_DLQ (
  RECORD_METADATA VARIANT,
  RECORD_CONTENT VARIANT,
  ERROR_MESSAGE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Verify setup
SELECT 'Setup Complete!' as STATUS;
SELECT CURRENT_ROLE() as ROLE, CURRENT_DATABASE() as DATABASE, CURRENT_SCHEMA() as SCHEMA;
SHOW TABLES IN SCHEMA SENTINEL_DB.STREAMING_SCHEMA;